version: '3'

services:

#PHP Service
  php:
    build: docker/php
    container_name: php_laravel
    restart: always
    volumes:
      - ./sources/backend:/var/www/html
    depends_on:
      - phpmyadmin
      - redis
    networks: 
      - net

  #Nginx Service
  webserver:
    build: docker/nginx
    container_name: nginx_laravel
    restart: always
    depends_on:
      - php
      - reactjs
    links:
      - reactjs
    ports:
      - "80:80"
    volumes:
      - ./sources/backend:/var/www/html
      - ./sources/frontend/build:/usr/share/nginx/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    networks: 
      - net
  
  # React Js
  reactjs:
    container_name: reactjs
    build:
      context: ./sources/frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - ./sources/frontend:/app
    networks:
      - net

  # React Js dev
  reactjs_dev:
    container_name: reactjs_dev
    build:
      context: ./sources/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./sources/frontend:/app
    networks:
      - net

  #MySQL Service
  mysql:
    image: mysql:8
    container_name: mysql_laravel
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    networks: 
      - net
   
  #PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_laravel
    restart: always
    ports:
      - "4040:80"
    volumes:
      - /sessions
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks: 
      - net

  #Redis
  redis:
    image: redis:latest
    container_name: redis_laravel
    ports:
      - 6379:6379
    networks: 
      - net

networks: 
  net: